apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: camel-quarkus
    app.kubernetes.io/component: camel-quarkus
    app.kubernetes.io/instance: camel-quarkus
  name: camel-quarkus
  namespace: gitops-demo
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: camel-quarkus:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: camel-quarkus
    git:
      uri: https://github.com/jcordes73/gitops-demo
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-11:1.3
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: TKc40q4egSyRhIbfxkNA
    type: GitHub
  - generic:
      secret: J2GhK7bsB-8MM6AiXKT-
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
