apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '21'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    gitops.ownedBy: gitops-demo
  name: cluster-configs
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: gitops-demo
  source:
    directory:
      recurse: true
    path: cluster
    repoURL: https://github.com/jcordes73/gitops-demo.git
    targetRevision: HEAD 
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
