apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-gitea
  namespace: openshift-gitops
spec:
  destination:
    namespace: gitops-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitea
    repoURL: https://github.com/jcordes73/gitops-demo.git
    targetRevision: HEAD 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
