apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: postgres
    template: postgresql-ephemeral-template
  name: postgres
  namespace: gitops-demo
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres
  sessionAffinity: None
  type: ClusterIP
